name: Build and Test Frontend Before Merge To Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  build-and-test-to-merge-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run Unit Tests
        working-directory: ./frontend
        run: npm run test

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
